{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tekla Modeling Ahyeon API (기본편)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "> 아현 푸르지오 모델링 진행 하면서 생산성을 향상 시킨 툴에 관한 설명서이다. \n",
    "> *(2021-04-02)*"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "> 기본편과 응용편으로 나누어진다. \n",
    "> 기본편은 여러 프로그램에 공통적으로 쓰인 함수를 위주로 설명하고\n",
    "> 응용편은 각 부재별 위주로 설명한다.\n",
    "> 추가적으로 REVIT API와 TEKLA API를 활용하여 REVIT과 TEKLA간의 골조모델 변환하는 방법도 작성 할 수 있길 희망한다.\n",
    "> *(2021-04-06)*"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 1.기본 Setting\n",
    "먼저 시작하기에 앞서 Visual Studio 기본 세팅을 해야한다. (Visual Stuidio와 Tekla는 설치되어 있다는 가정하에 진행한다.)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1.1 TEKLA 도구 설치\n",
    "\n",
    "    1. 도구>NuGet 패키지 관리자> 솔루션용 NuGet 패키지 관리 클릭"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<img src=\"TeklaNuget01.png\">"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "    2. 찾아보기> Tekla입력> 해당하는 버전 Down 설치 클릭 "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<img src=\"TeklaNuget02.png\">"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1.2 Using문을 활용한 기본 Tekla Class Import\n",
    "\n",
    "    1. 자주 사용하는 Class들을 Import한 것으로 프로그래머에 의해 조정가능하다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "//기본 Class\n",
    "using System;\n",
    "using System.Collections.Generic;\n",
    "using System.Linq;\n",
    "using System.Text;\n",
    "using System.Threading.Tasks;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(11,2): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(11,2): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "//테클라 코딩에 추가해야 할 부분\n",
    "using Tekla.Structures.Model;\n",
    "using Tekla.Structures.Geometry3d;\n",
    "using Tekla.Structures.Model.UI;\n",
    "using System.Diagnostics;\n",
    "using Tekla.Structures.Model.Operations;\n",
    "using System.Collections;\n",
    "using Tekla.Structures.Datatype;\n",
    "using Tekla.Structures.Solid;\n",
    "\n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2.주요 Reference 사이트\n",
    "Tekla API를 이용하는데 있어 참고할 만한 사이트 2곳을 추천한다."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "[테클라 API](https://developer.tekla.com/tekla-structures/api/14/8180)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "[실제 사용 예시들 Github 참고](https://github.com/razorcx )."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 3.주요 코드 설명\n",
    "아현푸르지오 프로젝트를 진행하면서 자주 사용하는 함수들을 우선 정리하고, 그 함수들을 이용하여 만든 프로그램을 설명하겠다. 후자는 참고사항이며, Refactoring이 필요하다. 기본 개념은 Diagram으로 표현할까 고민중이다."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.1 Part & RebarGroup 선택\n",
    "Tekla 화면에서 Part & RebarGroup을 선택하는 기본 명령이다. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(58,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(58,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "//하나의 객체를 선택할 때\n",
    "\n",
    "\n",
    "//Select Part\n",
    "var pickedObjectPart = new Picker()\n",
    "                    .PickObject(Picker.PickObjectEnum.PICK_ONE_PART, \"Select Part\");\n",
    "\n",
    "var part = pickedObjectPart as Part;\n",
    "\n",
    "\n",
    "//Select SingleRebar\n",
    "var pickedObjectRebar = new Picker()\n",
    "                    .PickObject(Picker.PickObjectEnum.PICK_ONE_REINFORCEMENT, \"Select Part\");\n",
    "\n",
    "var part = pickedObjectRebar as SingleRebar;\n",
    "\n",
    "\n",
    "//2개 이상의 객체를 선택할 때\n",
    "//자료형이 Enumerator라 Currnet()와 MoveNext()가 있어야 한다.\n",
    "//아래는 if while로 구현하였지만 foreach로 각각을 담는 방법도 있다고 한다. 이건 해봐야 한다.\n",
    "//자세한 내용은 아래 두 사이트를 참고\n",
    "//https://samsons.tistory.com/18\n",
    "//https://docs.microsoft.com/ko-kr/dotnet/api/system.collections.generic.list-1.enumerator?view=net-5.0\n",
    "\n",
    "\n",
    "//Select Multiple Parts\n",
    "var pickedObjectParts = new Picker()\n",
    "                .PickObjects(Picker.PickObjectsEnum.PICK_N_PARTS, \"Select Parts\");\n",
    "\n",
    "if (pickedObjects.GetSize() < 1) return;\n",
    "\n",
    "while (pickedObjects.MoveNext())\n",
    "    {\n",
    "\n",
    "        var rebar = pickedObjectParts.Current as Part;\n",
    "\n",
    "        if (rebar == null)\n",
    "            continue;\n",
    "    }\n",
    "\n",
    "//Select Multiple RebarGroup\n",
    "var pickedObjectRebarGroup = new Picker()\n",
    "                .PickObjects(Picker.PickObjectsEnum.PICK_N_REINFORCEMENTS, \"Select RebarGroup\");\n",
    "\n",
    "if (pickedObjects.GetSize() < 1) return;\n",
    "\n",
    "while (pickedObjects.MoveNext())\n",
    "    {\n",
    "\n",
    "        var rebar = pickedObjectRebarGroup.Current as RebarGroup;\n",
    "\n",
    "        if (rebar == null)\n",
    "            continue;\n",
    "\n",
    "\n",
    "    }\n",
    "\n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "> **위의 코드를 활용하여 RebarGroup의 FaterPart를 수정하는 예시.**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(32,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(32,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "public void ChangeFaterPart()\n",
    "        {\n",
    "            var pickedObjectPart = new Picker()\n",
    "                    .PickObject(Picker.PickObjectEnum.PICK_ONE_PART, \"Select Fater Part\");\n",
    "\n",
    "\n",
    "            var pickedObjects = new Picker()\n",
    "                .PickObjects(Picker.PickObjectsEnum.PICK_N_REINFORCEMENTS, \"Select RebarGroup\");\n",
    "\n",
    "            if (pickedObjects.GetSize() < 1) return;\n",
    "\n",
    "            while (pickedObjects.MoveNext())\n",
    "            {\n",
    "\n",
    "                var part = pickedObjectPart as Part;\n",
    "\n",
    "                var rebar = pickedObjects.Current as RebarGroup;\n",
    "\n",
    "                if (rebar == null)\n",
    "                    continue;\n",
    "\n",
    "                rebar.Father = part;\n",
    "\n",
    "                \n",
    "                rebar.Modify();\n",
    "\n",
    "\n",
    "            }\n",
    "            new Model().CommitChanges();\n",
    "        }\n",
    "\n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.2 Modify()와 Insert() \n",
    "Modify()와 Insert()는 유용하게 활용하면 Copy 기능을 활용하고 코드를 간결하게 만들 수 있는 도구이다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(37,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(37,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "//기둥에 Tie Bar를 모델링 할 경우 아래와 같이 Spacing을 TieBar의 갯수(strCount)만큼  \n",
    "//아래와 같이 rebar.Insert()를 하면 객체를 Copy하면서 만들어 나갈 수 있다.\n",
    "\n",
    "double spacing = 300;\n",
    "double strCount = 3;\n",
    "\n",
    "for (int i = 0; i < strCount; i++)\n",
    "        {\n",
    "            if (i == 0)\n",
    "            {\n",
    "\n",
    "                rebar.EndHook.Shape = RebarHookData.RebarHookShapeEnum.HOOK_90_DEGREES;\n",
    "                rebar.EndHook.Shape = RebarHookData.RebarHookShapeEnum.CUSTOM_HOOK;\n",
    "                rebar.EndHook.Angle = 90;\n",
    "                rebar.EndHook.Length = 75.47;\n",
    "                rebar.OnPlaneOffsets.Clear();\n",
    "                rebar.OnPlaneOffsets.Add(spacing);\n",
    "\n",
    "                rebar.Name = \"TIE\";\n",
    "\n",
    "                rebar.Modify();\n",
    "            }\n",
    "\n",
    "            else\n",
    "            {\n",
    "                rebar.EndHook.Shape = RebarHookData.RebarHookShapeEnum.HOOK_90_DEGREES;\n",
    "                rebar.EndHook.Shape = RebarHookData.RebarHookShapeEnum.CUSTOM_HOOK;\n",
    "                rebar.EndHook.Angle = 90;\n",
    "                rebar.EndHook.Length = 75.47;\n",
    "                rebar.OnPlaneOffsets.Clear();\n",
    "                rebar.OnPlaneOffsets.Add(spacing * (i+1));\n",
    "\n",
    "                rebar.Insert(); //TieBar의 갯수가 늘어날 때마다 Copy의 기능을 같이 수행한다.\n",
    "\n",
    "            }\n",
    "        }\n",
    "\n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.3 Create RebarGroup\n",
    "RebarGroup을 만드는 방법이다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(71,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(71,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "using Tekla.Structures.Model;\n",
    "using Tekla.Structures.Geometry3d;\n",
    "\n",
    "public class Example\n",
    "{\n",
    "       public void Example1()\n",
    "       {\n",
    "           Beam Beam = new Beam(new Point(5000, 8000, 0), new Point(6000, 8000, 0));\n",
    "           Beam.Profile.ProfileString = \"250*250\";\n",
    "           Beam.Material.MaterialString = \"K40-1\";\n",
    "           Beam.Finish = \"PAINT\";\n",
    "           Beam.Insert();\n",
    "\n",
    "           double MinimumX = Beam.GetSolid().MinimumPoint.X;\n",
    "           double MinimumY = Beam.GetSolid().MinimumPoint.Y;\n",
    "           double MinimumZ = Beam.GetSolid().MinimumPoint.Z;\n",
    "           double MaximumX = Beam.GetSolid().MaximumPoint.X;\n",
    "           double MaximumY = Beam.GetSolid().MaximumPoint.Y;\n",
    "           double MaximumZ = Beam.GetSolid().MaximumPoint.Z;\n",
    "\n",
    "           Polygon Polygon = new Polygon();\n",
    "           Polygon.Points.Add(new Point(MinimumX, MaximumY, MinimumZ));\n",
    "           Polygon.Points.Add(new Point(MinimumX, MinimumY, MinimumZ));\n",
    "           Polygon.Points.Add(new Point(MinimumX, MinimumY, MaximumZ));\n",
    "           Polygon.Points.Add(new Point(MinimumX, MaximumY, MaximumZ));\n",
    "\n",
    "           Polygon Polygon2 = new Polygon();\n",
    "           Polygon2.Points.Add(new Point(MaximumX, MaximumY, MinimumZ));\n",
    "           Polygon2.Points.Add(new Point(MaximumX, MinimumY, MinimumZ));\n",
    "           Polygon2.Points.Add(new Point(MaximumX, MinimumY, MaximumZ));\n",
    "           Polygon2.Points.Add(new Point(MaximumX, MaximumY, MaximumZ));\n",
    "\n",
    "           RebarGroup RebarGroup = new RebarGroup();\n",
    "           RebarGroup.Polygons.Add(Polygon);\n",
    "           RebarGroup.Polygons.Add(Polygon2);\n",
    "           RebarGroup.RadiusValues.Add(40.0);\n",
    "           RebarGroup.SpacingType = RebarGroup.RebarGroupSpacingTypeEnum.SPACING_TYPE_TARGET_SPACE;\n",
    "           RebarGroup.Spacings.Add(30.0);\n",
    "           RebarGroup.ExcludeType = RebarGroup.ExcludeTypeEnum.EXCLUDE_TYPE_BOTH;\n",
    "           RebarGroup.Father = Beam;\n",
    "           RebarGroup.Name = \"RebarGroup\";\n",
    "           RebarGroup.Class = 3;\n",
    "           RebarGroup.Size = \"12\";\n",
    "           RebarGroup.NumberingSeries.StartNumber = 0;\n",
    "           RebarGroup.NumberingSeries.Prefix = \"Group\";\n",
    "           RebarGroup.Grade = \"A500HW\";\n",
    "           RebarGroup.StartHook.Shape = RebarHookData.RebarHookShapeEnum.CUSTOM_HOOK;\n",
    "           RebarGroup.StartHook.Angle = -90;\n",
    "           RebarGroup.StartHook.Length = 3;\n",
    "           RebarGroup.StartHook.Radius = 20;\n",
    "           RebarGroup.EndHook.Shape = RebarHookData.RebarHookShapeEnum.CUSTOM_HOOK;\n",
    "           RebarGroup.EndHook.Angle = -90;\n",
    "           RebarGroup.EndHook.Length = 3;\n",
    "           RebarGroup.EndHook.Radius = 20;\n",
    "           RebarGroup.OnPlaneOffsets.Add(25.0);\n",
    "           RebarGroup.OnPlaneOffsets.Add(10.0);\n",
    "           RebarGroup.OnPlaneOffsets.Add(25.0);\n",
    "           RebarGroup.StartPointOffsetType = Reinforcement.RebarOffsetTypeEnum.OFFSET_TYPE_COVER_THICKNESS;\n",
    "           RebarGroup.StartPointOffsetValue = 20;\n",
    "           RebarGroup.EndPointOffsetType = Reinforcement.RebarOffsetTypeEnum.OFFSET_TYPE_COVER_THICKNESS;\n",
    "           RebarGroup.EndPointOffsetValue = 60;\n",
    "           RebarGroup.FromPlaneOffset = 40;\n",
    "\n",
    "           RebarGroup.Insert();\n",
    "\n",
    "           RebarGroup.Name = \"Modified Group 1\";\n",
    "           RebarGroup.Modify();\n",
    "       }\n",
    "}\n",
    "\n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.4 속성을 추출하는 방법\n",
    "Part & RebarGroup의 UserFields 속성을 추출하는 방법"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(89,14): error CS1513: }가 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(89,14): error CS1513: }가 필요합니다."
     ]
    }
   ],
   "source": [
    "public string UserFloorData(Part part)\n",
    "        {\n",
    "            var values = new Hashtable();\n",
    "            part.GetAllUserProperties(ref values);\n",
    "\n",
    "            // ifc story 스펠링 틀림 다른 프로젝트에서는 수정 필요\n",
    "            var partFloor = values[\"IFC_BUILDING_STOREY\"] as string;\n",
    "            //var partFloor = values[\"IFC_BUILDING\"] as string;\n",
    "            return partFloor;\n",
    "        }\n",
    "\n",
    "        public string UserBuildingData(Part part)\n",
    "        {\n",
    "            var values = new Hashtable();\n",
    "            part.GetAllUserProperties(ref values);\n",
    "\n",
    "            // ifc story 스펠링 틀림 다른 프로젝트에서는 수정 필요\n",
    "            var partFloor = values[\"IFC_BUILDING\"] as string;\n",
    "            return partFloor;\n",
    "        }\n",
    "\n",
    "\n",
    "        public string UserABC(Part part)\n",
    "        {\n",
    "            var values = new Hashtable();\n",
    "            part.GetAllUserProperties(ref values);\n",
    "\n",
    "            // ifc story 스펠링 틀림 다른 프로젝트에서는 수정 필요\n",
    "            var partFloor = values[\"BIMQ_SECTION\"] as string;\n",
    "            //var partFloor = values[\"IFC_BUILDING\"] as string;\n",
    "            return partFloor;\n",
    "        }\n",
    "\n",
    "        //Part Property대로 자동 기입\n",
    "        public void Run()\n",
    "        {\n",
    "            var pickedObjects = new Picker()\n",
    "                    .PickObjects(Picker.PickObjectsEnum.PICK_N_PARTS);\n",
    "\n",
    "            if (pickedObjects.GetSize() < 1) return;\n",
    "\n",
    "            while (pickedObjects.MoveNext())\n",
    "            {\n",
    "\n",
    "\n",
    "                var part = pickedObjects.Current as Part;\n",
    "                if (part == null)\n",
    "                    continue;\n",
    "\n",
    "\n",
    "                string buildingDataUser3 = UserABC(part);\n",
    "                part.SetUserProperty(\"USER_FIELD_3\", buildingDataUser3);\n",
    "\n",
    "                \n",
    "                string buildingData = UserBuildingData(part);\n",
    "                string floorData = UserFloorData(part);\n",
    "\n",
    "                part.SetUserProperty(\"USER_FIELD_1\", buildingData);\n",
    "                part.SetUserProperty(\"BIMQ_FLOOR\", floorData);\n",
    "\n",
    "                //Part에 속한 RebarGroup or 모델들 추출 나중에 delete 기존거 해야한다.\n",
    "                ModelObjectEnumerator rebarModelHierarchic = part.GetChildren();\n",
    "                foreach (var obj in rebarModelHierarchic)\n",
    "                {\n",
    "                    if (obj != null)\n",
    "                    {\n",
    "                        \n",
    "                        RebarGroup rebarGroup = new RebarGroup();\n",
    "                        rebarGroup = obj as RebarGroup;\n",
    "\n",
    "                        if (rebarGroup != null)\n",
    "                        {\n",
    "                            rebarGroup.SetUserProperty(\"USER_FIELD_1\", buildingData);\n",
    "                            rebarGroup.SetUserProperty(\"USER_FIELD_2\", floorData);\n",
    "\n",
    "                            rebarGroup.SetUserProperty(\"BIMQ_FLOOR\", floorData);\n",
    "\n",
    "                            rebarGroup.SetUserProperty(\"BIMQ_SECTION\", buildingDataUser3);\n",
    "                        }\n",
    "                    }\n",
    "                }\n",
    "                \n",
    "\n",
    "                new Model().CommitChanges();\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "            }\n",
    "            \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(17,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(17,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "//전체 키값들 추출\n",
    "\n",
    "public double UserFloorData(Part part)\n",
    "        {\n",
    "            var values = new Hashtable();\n",
    "            part.GetAllUserProperties(ref values);\n",
    "\n",
    "\n",
    "            Console.Write(\"3. 키값들만 출력\\n\\t\");\n",
    "            ICollection mykey = values.Keys;\n",
    "\n",
    "            foreach (object obj in mykey)\n",
    "                Console.Write(\"{0},\", obj);\n",
    "            return floorNumber;\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.5 Array에서 최댓값,최솟값,세번째 값 추출하는 방법\n",
    "Array의 내의 첫번째 값과 세번째 값을 추출할 수 있으면 Slab 배근 할 때 유용"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "public ArrayList MinMaxValue(ArrayList distanceArray)\n",
    "        {\n",
    "\n",
    "            ArrayList arrayList = new ArrayList();\n",
    "            int max = int.MinValue;\n",
    "            int min = int.MaxValue;\n",
    "            int maxIndex = 0;\n",
    "            int minIndex = 0;\n",
    "            \n",
    "\n",
    "            for (int i = 0; i < distanceArray.Count; i++)\n",
    "            {\n",
    "                if (Convert.ToInt32(distanceArray[i]) > max)\n",
    "                {\n",
    "                    max = Convert.ToInt32(distanceArray[i]);\n",
    "                    maxIndex = i;\n",
    "                }\n",
    "                if (Convert.ToDouble(distanceArray[i]) < min)\n",
    "                {\n",
    "                    min = Convert.ToInt32(distanceArray[i]);\n",
    "                    minIndex = i;\n",
    "                }\n",
    "\n",
    "            }\n",
    "\n",
    "            arrayList.Add(max);\n",
    "            arrayList.Add(min);\n",
    "            arrayList.Add(maxIndex);\n",
    "            arrayList.Add(minIndex);\n",
    "\n",
    "            return arrayList;\n",
    "\n",
    "        }\n",
    "\n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "public ArrayList FisrtThirdValue(ArrayList distanceArray)\n",
    "        {\n",
    "\n",
    "            ArrayList arrayList = new ArrayList();\n",
    "            ArrayList sortList = new ArrayList(distanceArray);\n",
    "            int max = int.MinValue;\n",
    "            int third = int.MinValue;\n",
    "            int maxIndex =1;\n",
    "            int thirdIndex = 1;\n",
    "            int countArray = distanceArray.Count;\n",
    "\n",
    "            distanceArray.Sort();\n",
    "\n",
    "            \n",
    "\n",
    "\n",
    "                for (int i = 0; i < sortList.Count; i++)\n",
    "            {\n",
    "                if (Convert.ToInt32(distanceArray[countArray-1]) == Convert.ToInt32(sortList[i]))\n",
    "                {\n",
    "                    max = Convert.ToInt32(sortList[i]);\n",
    "                    maxIndex = i;\n",
    "                    \n",
    "                }\n",
    "                else if (Convert.ToInt32(distanceArray[countArray-3]) == Convert.ToInt32(sortList[i]))\n",
    "                {\n",
    "                    third = Convert.ToInt32(sortList[i]);\n",
    "                    thirdIndex = i;\n",
    "                    \n",
    "                }\n",
    "\n",
    "            }\n",
    "\n",
    "\n",
    "           \n",
    "            if (maxIndex != countArray - 1)\n",
    "            {\n",
    "                arrayList.Add(maxIndex);\n",
    "                arrayList.Add(maxIndex + 1);\n",
    "            }\n",
    "            else\n",
    "            {\n",
    "                arrayList.Add(maxIndex);\n",
    "                arrayList.Add(0);\n",
    "            }\n",
    "\n",
    "            if (thirdIndex != countArray - 1)\n",
    "            {\n",
    "                arrayList.Add(thirdIndex); \n",
    "                arrayList.Add(thirdIndex + 1);\n",
    "            }\n",
    "            else\n",
    "            {\n",
    "                arrayList.Add(thirdIndex);\n",
    "                arrayList.Add(0);\n",
    "            }\n",
    "\n",
    "\n",
    "            \n",
    "            \n",
    "            return arrayList;\n",
    "\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.6 두 점을 이용하여 거리, 특정점을 추출하는 방법\n",
    "두 점 사이의 거리를 이용하여 특정점 혹은 거리를 구하는 방법"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//거리 구하기\n",
    "\n",
    "public double PointDistance(Point pt1, Point pt2)\n",
    "        {\n",
    "            double pointDistance = Math.Sqrt(Math.Pow(pt1.X - pt2.X, 2) + Math.Pow(pt1.Y - pt2.Y, 2) + Math.Pow(pt1.Z - pt2.Z, 2));\n",
    "\n",
    "            return pointDistance;\n",
    "        }\n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//1/3 지점 추출 parameterPercent에 0.3 입력하면 된다.\n",
    "\n",
    "public Point RebarPointThreeFirst(Point startPoint, Point endPoint, double parameterPercent)\n",
    "        {\n",
    "\n",
    "            double threeFisrtX = 0;\n",
    "            double threeFisrtY = 0;\n",
    "            double threeFisrtZ = 0;\n",
    "\n",
    "            if (startPoint.X < endPoint.X)\n",
    "            {\n",
    "                threeFisrtX = Math.Abs(startPoint.X - endPoint.X) * parameterPercent + startPoint.X;\n",
    "            }\n",
    "            else\n",
    "            {\n",
    "                threeFisrtX = Math.Abs(startPoint.X - endPoint.X) * (-1 * parameterPercent) + startPoint.X;\n",
    "            }\n",
    "\n",
    "\n",
    "            if (startPoint.Y < endPoint.Y)\n",
    "            {\n",
    "                threeFisrtY = Math.Abs(startPoint.Y - endPoint.Y) * parameterPercent + startPoint.Y;\n",
    "            }\n",
    "            else\n",
    "            {\n",
    "                threeFisrtY = Math.Abs(startPoint.Y - endPoint.Y) * (-1 * parameterPercent) + startPoint.Y;\n",
    "            }\n",
    "\n",
    "\n",
    "            if (startPoint.Z < endPoint.Z)\n",
    "            {\n",
    "                threeFisrtZ = Math.Abs(startPoint.Z - endPoint.Z) * parameterPercent + startPoint.Z;\n",
    "            }\n",
    "            else\n",
    "            {\n",
    "                threeFisrtZ = Math.Abs(startPoint.Z - endPoint.Z) * (-1 * parameterPercent) + startPoint.Z;\n",
    "            }\n",
    "\n",
    "            Point point = new Point(threeFisrtX, threeFisrtY, threeFisrtZ);\n",
    "\n",
    "            return point;\n",
    "\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//1/3 지점 추출 parameterPercent에 0.3 입력하면 된다.\n",
    "\n",
    "\n",
    "public Point RebarPointThreeFirstReverse(Point startPoint, Point endPoint, double parameterPercent)\n",
    "        {\n",
    "\n",
    "            double threeFisrtX = 0;\n",
    "            double threeFisrtY = 0;\n",
    "            double threeFisrtZ = 0;\n",
    "\n",
    "            if (startPoint.X > endPoint.X)\n",
    "            {\n",
    "                threeFisrtX = Math.Abs(startPoint.X - endPoint.X) * parameterPercent + startPoint.X;\n",
    "            }\n",
    "            else\n",
    "            {\n",
    "                threeFisrtX = Math.Abs(startPoint.X - endPoint.X) * (-1 * parameterPercent) + startPoint.X;\n",
    "            }\n",
    "\n",
    "\n",
    "            if (startPoint.Y > endPoint.Y)\n",
    "            {\n",
    "                threeFisrtY = Math.Abs(startPoint.Y - endPoint.Y) * parameterPercent + startPoint.Y;\n",
    "            }\n",
    "            else\n",
    "            {\n",
    "                threeFisrtY = Math.Abs(startPoint.Y - endPoint.Y) * (-1 * parameterPercent) + startPoint.Y;\n",
    "            }\n",
    "\n",
    "\n",
    "            if (startPoint.Z > endPoint.Z)\n",
    "            {\n",
    "                threeFisrtZ = Math.Abs(startPoint.Z - endPoint.Z) * parameterPercent + startPoint.Z;\n",
    "            }\n",
    "            else\n",
    "            {\n",
    "                threeFisrtZ = Math.Abs(startPoint.Z - endPoint.Z) * (-1 * parameterPercent) + startPoint.Z;\n",
    "            }\n",
    "\n",
    "            Point point = new Point(threeFisrtX, threeFisrtY, threeFisrtZ);\n",
    "\n",
    "            return point;\n",
    "\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Point thirtyPointFisrt = new Point();\n",
    "                Point thirtyPointSecond = new Point();\n",
    "\n",
    "                double distanceValue = PointDistance(firstPoint, secondPoint);\n",
    "                double distanceValueSecond = PointDistance(secondPoint, thirdPoint);\n",
    "\n",
    "                double percentValue = 0;\n",
    "                double percentValueSecond = 0;\n",
    "\n",
    "                //거리가 350이 되는 곳의 점을 찾아서 해당 점을 찾는 것이다.\n",
    "                if (distanceValue <= 350)\n",
    "                {\n",
    "                    percentValue = (350 - distanceValue) / distanceValue;\n",
    "                    thirtyPointFisrt = RebarPointThreeFirstReverse(firstPoint, secondPoint, percentValue);\n",
    "\n",
    "                }\n",
    "                else\n",
    "                {\n",
    "                    percentValue = 1 - (350 / distanceValue);\n",
    "                    thirtyPointFisrt = RebarPointThreeFirst(firstPoint, secondPoint, percentValue);\n",
    "\n",
    "                }\n",
    "                // 2번째\n",
    "                if (distanceValueSecond <= 350)\n",
    "                {\n",
    "                    percentValueSecond = (350 - distanceValueSecond) / distanceValueSecond;\n",
    "                    thirtyPointSecond = RebarPointThreeFirstReverse(secondPoint, thirdPoint, percentValueSecond);\n",
    "\n",
    "                }\n",
    "                else\n",
    "                {\n",
    "                    percentValueSecond = (350 / distanceValueSecond);\n",
    "                    thirtyPointSecond = RebarPointThreeFirst(secondPoint, thirdPoint, percentValueSecond);\n",
    "\n",
    "                }\n",
    "\n",
    "                polygon.Points[0] = thirtyPointFisrt;\n",
    "                polygon.Points[1] = secondPoint;\n",
    "                polygon.Points.Add(thirtyPointSecond);\n",
    "\n",
    "                rebar.EndHook.Shape = RebarHookData.RebarHookShapeEnum.CUSTOM_HOOK;\n",
    "                rebar.EndHook.Angle = 0;\n",
    "                rebar.EndHook.Length = 0;\n",
    "                rebar.EndHook.Radius = 0;\n",
    "                rebar.EndPointOffsetValue = 0;\n",
    "\n",
    "\n",
    "                rebar.Polygons[0] = polygon;\n",
    "                rebar.Class = 1;\n",
    "\n",
    "                rebar.Insert();\n",
    "                \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.7 Solid 객체의 각 점을 추출하는 방법(Vector 활용)\n",
    "MxPt와 MnPt는 객체의 Offset 값이 적용되어 있을 때 부정확한 값을 반환한다. 따라서 Solid 객체를 이용하여 Point를 반환하는 것이 정확하다. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "                Point beamMaxPoint = part.GetSolid().MaximumPoint as Point;\n",
    "                Point beamMinPoint = part.GetSolid().MinimumPoint as Point;\n",
    "\n",
    "                //Face 추출 Refactoring 필요\n",
    "                //이 부분이 Solid에서 Vector를 이용해 Face를 추출하는 부분이다. Offset이 있는 부분에서는 이와 같은 방법을 사용해야 한다.\n",
    "\n",
    "                List<Point> facePointTop = new List<Point>();\n",
    "                List<Point> facePointBot = new List<Point>();\n",
    "\n",
    "                Solid solid = part.GetSolid();\n",
    "                FaceEnumerator faceEnumerator = solid.GetFaceEnumerator();\n",
    "\n",
    "                Face faceTop = faceEnumerator.Current as Face;\n",
    "\n",
    "                while (faceEnumerator.MoveNext())\n",
    "                {\n",
    "                    var face = faceEnumerator.Current as Face;\n",
    "\n",
    "                    if (face.Normal.Z >= 0.990 && face.Normal.Z <= 1.010)\n",
    "                    {\n",
    "                        faceTop = face as Face;\n",
    "                    }\n",
    "\n",
    "                }\n",
    "\n",
    "                faceEnumerator.Reset();\n",
    "                faceEnumerator.MoveNext();\n",
    "\n",
    "                LoopEnumerator loopEnumeratorTop = faceTop.GetLoopEnumerator();\n",
    "\n",
    "\n",
    "                //TopPoint\n",
    "                while (loopEnumeratorTop.MoveNext())\n",
    "                {\n",
    "                    var pointFaceTop = loopEnumeratorTop.Current as Loop;\n",
    "\n",
    "                    VertexEnumerator vertexEnumeratorTop = pointFaceTop.GetVertexEnumerator();\n",
    "\n",
    "                    while (vertexEnumeratorTop.MoveNext())\n",
    "                    {\n",
    "                        facePointTop.Add(vertexEnumeratorTop.Current);\n",
    "                    }\n",
    "                    vertexEnumeratorTop.Reset();\n",
    "                    vertexEnumeratorTop.MoveNext();\n",
    "                }\n",
    "                loopEnumeratorTop.Reset();\n",
    "                loopEnumeratorTop.MoveNext();\n",
    "\n",
    "                foreach (Point i in facePointTop)\n",
    "                {\n",
    "                    Point pointBot = new Point(i.X, i.Y, beamMinPoint.Z);\n",
    "                    facePointBot.Add(pointBot);\n",
    "                }\n",
    "\n",
    "                //Edge 추출 끝\n",
    "                \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.8 철근정착길이, 이음길이를 적용\n",
    "D10, D13 등 각 철근마다 콘크리트의 Material과 정착 방법, 이음에 따라 나누어진다. 이를 if문으로 정리 한 것이다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//0도 정착\n",
    "\n",
    "public double ZeroSettleRebar(string size, string partMaterial)\n",
    "        {\n",
    "\n",
    "            double zeroSettle = 0;\n",
    "\n",
    "            if (size == \"10\")\n",
    "            {\n",
    "                zeroSettle = 300;\n",
    "            }\n",
    "            else if (size == \"13\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                zeroSettle = 380;\n",
    "            }\n",
    "            else if (size == \"13\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                zeroSettle = 360;\n",
    "            }\n",
    "            else if (size == \"16\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                zeroSettle = 570;\n",
    "            }\n",
    "            else if (size == \"16\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                zeroSettle = 530;\n",
    "            }\n",
    "            else if (size == \"19\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                zeroSettle = 680;\n",
    "            }\n",
    "            else if (size == \"19\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                zeroSettle = 640;\n",
    "            }\n",
    "\n",
    "            zeroSettle = zeroSettle * -1;\n",
    "\n",
    "            return zeroSettle;\n",
    "\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//90도 정착\n",
    "\n",
    "public double RightSettleRebar(string size, string partMaterial)\n",
    "        {\n",
    "\n",
    "            double rightSettle = 0;\n",
    "\n",
    "            \n",
    "            if (size == \"10\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                rightSettle = 170;\n",
    "            }\n",
    "            else if (size == \"10\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                rightSettle = 160;\n",
    "            }\n",
    "            else if (size == \"13\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                rightSettle = 220;\n",
    "            }\n",
    "            else if (size == \"13\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                rightSettle = 210;\n",
    "            }\n",
    "            else if (size == \"16\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                rightSettle = 330;\n",
    "            }\n",
    "            else if (size == \"16\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                rightSettle = 310;\n",
    "            }\n",
    "            else if (size == \"19\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                rightSettle = 400;\n",
    "            }\n",
    "            else if (size == \"19\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                rightSettle = 380;\n",
    "            }\n",
    "\n",
    "            rightSettle = rightSettle * -1;\n",
    "\n",
    "            return rightSettle;\n",
    "\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//이음\n",
    "\n",
    "public double ZeroConnectRebar(string size, string partMaterial)\n",
    "        {\n",
    "\n",
    "            double zeroConnect = 0;\n",
    "\n",
    "\n",
    "            if (size == \"10\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                zeroConnect = 370;\n",
    "            }\n",
    "            else if (size == \"10\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                zeroConnect = 350;\n",
    "            }\n",
    "            else if (size == \"13\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                zeroConnect = 490;\n",
    "            }\n",
    "            else if (size == \"13\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                zeroConnect = 460;\n",
    "            }\n",
    "            else if (size == \"16\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                zeroConnect = 730;\n",
    "            }\n",
    "            else if (size == \"16\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                zeroConnect = 690;\n",
    "            }\n",
    "            else if (size == \"19\" && partMaterial == \"C24\")\n",
    "            {\n",
    "                zeroConnect = 880;\n",
    "            }\n",
    "            else if (size == \"19\" && partMaterial == \"C27\")\n",
    "            {\n",
    "                zeroConnect = 830;\n",
    "            }\n",
    "\n",
    "            zeroConnect = zeroConnect * -1;\n",
    "\n",
    "            return zeroConnect;\n",
    "\n",
    "        }\n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.9 엑셀에서 데이터를 가져오는 방법\n",
    "Excel을 통해 데이터를 가져오는 방법이다. Nuget Package에서 LinqToExcel 다운 받아야 한다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(2,7): error CS0246: LinqToExcel' 형식 또는 네임스페이스 이름을 찾을 수 없습니다. using 지시문 또는 어셈블리 참조가 있는지 확인하세요.",
     "output_type": "error",
     "traceback": [
      "(2,7): error CS0246: LinqToExcel' 형식 또는 네임스페이스 이름을 찾을 수 없습니다. using 지시문 또는 어셈블리 참조가 있는지 확인하세요."
     ]
    }
   ],
   "source": [
    "using System.Linq;\n",
    "using LinqToExcel;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(26,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(26,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "    public class ConnexionExcel\n",
    "    {\n",
    "        public string _pathExcelFile;\n",
    "        public ExcelQueryFactory _urlConnexion;\n",
    "        public ConnexionExcel(string path)\n",
    "        {\n",
    "            this._pathExcelFile = path;\n",
    "            this._urlConnexion = new ExcelQueryFactory(_pathExcelFile);\n",
    "        }\n",
    "        public string PathExcelFile\n",
    "        {\n",
    "            get\n",
    "            {\n",
    "                return _pathExcelFile;\n",
    "            }\n",
    "        }\n",
    "        public ExcelQueryFactory UrlConnexion\n",
    "        {\n",
    "            get\n",
    "            {\n",
    "                return _urlConnexion;\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "    \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "   //엑셀 Column 각 Name에 맞게 추출\n",
    "   \n",
    "   public class SlabData\n",
    "    {\n",
    "        public string NAME\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "        public string SLAB_BOT\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "        public string SLAB_TOP\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "        public string TYPE\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "        public string X1\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "        public string X2\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "        public string X3\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "        public string X4\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "        public string Y1\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "        public string Y2\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "        public string Y3\n",
    "        {\n",
    "            get;\n",
    "            set;\n",
    "        }\n",
    "\n",
    "\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "public List<string> ExcelToLinqData(Part part)\n",
    "        {\n",
    "            string pathToExcelFile = @\"D:\\Project\\아현 푸르지오\\BASEMENTSLABREBAR.xlsx\";\n",
    "            ConnexionExcel ConxObject = new ConnexionExcel(pathToExcelFile);\n",
    "\n",
    "            List<string> RebarXYValue = new List<string>();\n",
    "\n",
    "            double floorData = IFCFloorData(part);\n",
    "\n",
    "            var query1 = from a in ConxObject.UrlConnexion.Worksheet<SlabData>()\n",
    "                         where a.NAME.Contains(\"S\")\n",
    "                         select a;\n",
    "\n",
    "\n",
    "            // index 0 = TOPShort, 1 = BOTShort, 2 = TOPLong, 3 = BOTLong\n",
    "\n",
    "            foreach (var result in query1)\n",
    "            {\n",
    "\n",
    "                if (part.Finish == result.NAME && Convert.ToInt32(floorData) >= Convert.ToInt32(result.SLAB_BOT) && Convert.ToInt32(floorData) <= Convert.ToInt32(result.SLAB_TOP))\n",
    "                {\n",
    "\n",
    "                    if (result.TYPE == \"A\")\n",
    "                    {\n",
    "                        RebarXYValue.Add(result.X1);\n",
    "                        RebarXYValue.Add(result.X3);\n",
    "                        RebarXYValue.Add(result.Y1);\n",
    "                        RebarXYValue.Add(result.Y3);\n",
    "\n",
    "                    }\n",
    "                    else if(result.TYPE == \"C\")\n",
    "                    {\n",
    "                        RebarXYValue.Add(result.X3);\n",
    "                        RebarXYValue.Add(result.X1);\n",
    "                        RebarXYValue.Add(result.Y3);\n",
    "                        RebarXYValue.Add(result.Y1);\n",
    "                        // TYPE에 따라 X1 X3 의 상부하부가 다르다.\n",
    "                    }\n",
    "                    else\n",
    "                    {\n",
    "                        RebarXYValue.Add(\"10/300\");\n",
    "                        RebarXYValue.Add(\"10/300\");\n",
    "                        RebarXYValue.Add(\"10/300\");\n",
    "                        RebarXYValue.Add(\"10/300\");\n",
    "\n",
    "                        //일람에 없으면 10/300으로 통일\n",
    "\n",
    "                    }\n",
    "\n",
    "                }\n",
    "                \n",
    "            }\n",
    "\n",
    "            return RebarXYValue;\n",
    "\n",
    "        }\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.10 해당하는 파트의 RebarGroup을 삭제하는 방법\n",
    "각 파트에 속한 객체를 수정하기 어려울 때는 아예 Delete()하여 새로 그리는 것이 빠르다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(42,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(42,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "public void DELETE()\n",
    "        {\n",
    "            var pickedObjects = new Picker()\n",
    "                    .PickObjects(Picker.PickObjectsEnum.PICK_N_PARTS);\n",
    "\n",
    "            if (pickedObjects.GetSize() < 1) return;\n",
    "\n",
    "            while (pickedObjects.MoveNext())\n",
    "            {\n",
    "\n",
    "\n",
    "                var part = pickedObjects.Current as Part;\n",
    "                if (part == null)\n",
    "                    continue;\n",
    "\n",
    "\n",
    "\n",
    "                //Part에 속한 RebarGroup or 모델들 추출 나중에 delete 기존거 해야한다.\n",
    "                ModelObjectEnumerator rebarModelHierarchic = part.GetChildren();\n",
    "                foreach (var obj in rebarModelHierarchic)\n",
    "                {\n",
    "                    if (obj != null)\n",
    "                    {\n",
    "                        RebarGroup rebarGroup = new RebarGroup();\n",
    "                        rebarGroup = obj as RebarGroup;\n",
    "\n",
    "                        if (rebarGroup != null)\n",
    "                        {\n",
    "                            rebarGroup.Delete();\n",
    "                        }\n",
    "                    }\n",
    "                }\n",
    "\n",
    "                new Model().CommitChanges();\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "            }\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.11 RebarGroup이 Part를 벗어날 때 Part 안으로 위치시키는 방법\n",
    "슬라브나 보 등의 부재안에 RebarGroup을 그릴 때 값을 음수 혹은 양수로 주어야 하는 경우가 있다. 이를 if문으로 가려낼 수 있다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "public RebarGroup RebarGroupCorrection(RebarGroup rebarGroup, Point MinMaxPoint)\n",
    "        {\n",
    "\n",
    "            double rebarGroupTOPPointZ = rebarGroup.GetSolid().MaximumPoint.Z;\n",
    "            double rebarGroupBOTPointZ = rebarGroup.GetSolid().MinimumPoint.Z;\n",
    "            double cover = Convert.ToDouble(rebarGroup.OnPlaneOffsets[0]);\n",
    "\n",
    "            if (rebarGroup.Name.Contains(\"TOP\"))\n",
    "            {\n",
    "\n",
    "                if (MinMaxPoint.Z < rebarGroupTOPPointZ)\n",
    "                {\n",
    "                    rebarGroup.OnPlaneOffsets.Clear();\n",
    "                    rebarGroup.OnPlaneOffsets.Add(cover * -1);\n",
    "                    rebarGroup.Modify();\n",
    "                }\n",
    "\n",
    "\n",
    "            }\n",
    "            else if (rebarGroup.Name.Contains(\"BOT\"))\n",
    "            {\n",
    "                if (MinMaxPoint.Z > rebarGroupBOTPointZ)\n",
    "                {\n",
    "                    rebarGroup.OnPlaneOffsets.Clear();\n",
    "                    rebarGroup.OnPlaneOffsets.Add(cover * -1);\n",
    "                    rebarGroup.Modify();\n",
    "                }\n",
    "\n",
    "            }\n",
    "\n",
    "\n",
    "            return rebarGroup;\n",
    "\n",
    "\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.12 내부와 외부를 구분하는 방법\n",
    "Pt를 기준으로, 지하외벽의 피복두께를 고려한 모델링을 할 때 유용하다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(38,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(38,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "                            Point rebarGroupPoint1 = RebarGroup.GetSolid().MaximumPoint as Point;\n",
    "\t\t\t\t\t\t\tPoint rebarGroupPoint2 = RebarGroup.GetSolid().MinimumPoint as Point;\n",
    "\t\t\t\t\t\t\tPoint rebarGroupCopyPoint1 = RebarGroupCopy.GetSolid().MaximumPoint as Point;\n",
    "\t\t\t\t\t\t\tPoint rebarGroupCopyPoint2 = RebarGroupCopy.GetSolid().MinimumPoint as Point;\n",
    "\n",
    "\n",
    "\t\t\t\t\t\t\tPoint rebarPoint1 = new Point((rebarGroupPoint1.X + rebarGroupPoint2.X) / 2, (rebarGroupPoint1.Y + rebarGroupPoint2.Y) / 2, (rebarGroupPoint1.Z + rebarGroupPoint2.Z) / 2);\n",
    "\t\t\t\t\t\t\tPoint rebarPoint2 = new Point((rebarGroupCopyPoint1.X + rebarGroupCopyPoint2.X) / 2, (rebarGroupCopyPoint1.Y + rebarGroupCopyPoint2.Y) / 2, (rebarGroupCopyPoint1.Z + rebarGroupCopyPoint2.Z) / 2);\n",
    "\t\t\t\t\t\t\tPoint centerPoint = new Point(49800, 19300, 29840);\n",
    "\n",
    "\n",
    "\t\t\t\t\t\t\tdouble pointDistance1 = Math.Pow(centerPoint.X - rebarPoint1.X, 2) + Math.Pow(centerPoint.Y - rebarPoint1.Y, 2);\n",
    "\t\t\t\t\t\t\tdouble pointDistance2 = Math.Pow(centerPoint.X - rebarPoint2.X, 2) + Math.Pow(centerPoint.Y - rebarPoint2.Y, 2);\n",
    "\n",
    "\t\t\t\t\t\t\tif (pointDistance1 < pointDistance2)\n",
    "\t\t\t\t\t\t\t{\n",
    "\t\t\t\t\t\t\t\tRebarGroup.OnPlaneOffsets.Clear();\n",
    "\t\t\t\t\t\t\t\tRebarGroup.OnPlaneOffsets.Add(Convert.ToDouble(profileSplit[1]) / 2 - 50);\n",
    "\t\t\t\t\t\t\t\tRebarGroup.Size = widthRebarIN;\n",
    "\t\t\t\t\t\t\t\tRebarGroup.Spacings.Clear();\n",
    "\t\t\t\t\t\t\t\tRebarGroup.Spacings.Add(spacingRebarDoubleIN);\n",
    "\t\t\t\t\t\t\t\tRebarGroup.EndPointOffsetValue = rebarLengthEndIN;\n",
    "\n",
    "\t\t\t\t\t\t\t\tRebarGroup.Modify();\n",
    "\n",
    "\t\t\t\t\t\t\t\tRebarGroupCopy.OnPlaneOffsets.Clear();\n",
    "\t\t\t\t\t\t\t\tRebarGroupCopy.OnPlaneOffsets.Add(Convert.ToDouble(profileSplit[1]) / 2 - 70);\n",
    "\t\t\t\t\t\t\t\tRebarGroupCopy.Size = widthRebarOUT;\n",
    "\t\t\t\t\t\t\t\tRebarGroupCopy.Spacings.Clear();\n",
    "\t\t\t\t\t\t\t\tRebarGroupCopy.Spacings.Add(spacingRebarDoubleOUT);\n",
    "\t\t\t\t\t\t\t\tRebarGroupCopy.EndPointOffsetValue = rebarLengthEndOUT;\n",
    "\n",
    "\t\t\t\t\t\t\t\tRebarGroupCopy.Modify();\n",
    "\n",
    "\n",
    "                            }\n",
    "                            \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.13 RebarGroup의 높이를 수정하는 방법(StartPt,EndPt, Polygon, Range)\n",
    "지하 외벽에 Copy를 할 때 높이가 달라지는 부분을 각 Part의 높이에 맞게 수정해야 한다. 이때 이러한 방법을 사용하면 유용하다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "        public void HeightModify()\n",
    "        {\n",
    "\n",
    "            var pickedObjectPart = new Picker()\n",
    "                    .PickObject(Picker.PickObjectEnum.PICK_ONE_PART, \"Select Fater Part\");\n",
    "\n",
    "\n",
    "            var pickedObjects = new Picker()\n",
    "                .PickObjects(Picker.PickObjectsEnum.PICK_N_REINFORCEMENTS);\n",
    "            if (pickedObjects.GetSize() < 1) return;\n",
    "\n",
    "            while (pickedObjects.MoveNext())\n",
    "            {\n",
    "\n",
    "                var part = pickedObjectPart as Part;\n",
    "\n",
    "                var rebar = pickedObjects.Current as RebarGroup;\n",
    "\n",
    "                if (rebar == null)\n",
    "                    continue;\n",
    "\n",
    "                string profileHeight = part.Profile.ProfileString;\n",
    "                profileHeight = profileHeight.Split('X')[0];\n",
    "\n",
    "                rebar.Father = part;\n",
    "                VERHeight(rebar, Convert.ToDouble(profileHeight));\n",
    "\n",
    "                rebar.Modify();\n",
    "\n",
    "\n",
    "            }\n",
    "            new Model().CommitChanges();\n",
    "        }\n",
    "\n",
    "        public void HeightModifyHOR()\n",
    "        {\n",
    "\n",
    "            var pickedObjectPart = new Picker()\n",
    "                    .PickObject(Picker.PickObjectEnum.PICK_ONE_PART, \"Select Fater Part\");\n",
    "\n",
    "\n",
    "            var pickedObjects = new Picker()\n",
    "                .PickObjects(Picker.PickObjectsEnum.PICK_N_REINFORCEMENTS);\n",
    "            if (pickedObjects.GetSize() < 1) return;\n",
    "\n",
    "            while (pickedObjects.MoveNext())\n",
    "            {\n",
    "\n",
    "                var part = pickedObjectPart as Part;\n",
    "\n",
    "                var rebar = pickedObjects.Current as RebarGroup;\n",
    "\n",
    "                if (rebar == null)\n",
    "                    continue;\n",
    "\n",
    "                string profileHeight = part.Profile.ProfileString;\n",
    "                profileHeight = profileHeight.Split('X')[0];\n",
    "\n",
    "                rebar.Father = part;\n",
    "                HORHeight(rebar, Convert.ToDouble(profileHeight));\n",
    "\n",
    "                rebar.Modify();\n",
    "\n",
    "\n",
    "            }\n",
    "            new Model().CommitChanges();\n",
    "        }\n",
    "\n",
    "        public void VERHeight(RebarGroup rebar, double a)\n",
    "        {\n",
    "\n",
    "\n",
    "            Polygon polygon = new Polygon();\n",
    "            Point pointStart = new Point();\n",
    "\n",
    "            polygon = rebar.Polygons[0] as Polygon;\n",
    "\n",
    "            pointStart = polygon.Points[0] as Point;\n",
    "            Point pointEnd = new Point(pointStart.X, pointStart.Y, pointStart.Z + a);\n",
    "\n",
    "\n",
    "\n",
    "            polygon.Points[0] = pointStart;\n",
    "            polygon.Points[1] = pointEnd;\n",
    "\n",
    "            rebar.Polygons[0] = polygon;\n",
    "\n",
    "            rebar.Modify();\n",
    "\n",
    "        }\n",
    "\n",
    "        public void HORHeight(RebarGroup rebar, double a)\n",
    "        {\n",
    "\n",
    "            Point pointStart = new Point();\n",
    "\n",
    "            pointStart = rebar.StartPoint as Point;\n",
    "            Point pointEnd = new Point(pointStart.X, pointStart.Y, pointStart.Z + a);\n",
    "\n",
    "            rebar.EndPoint = pointEnd;\n",
    "\n",
    "            rebar.Modify();\n",
    "\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3.14 강종을 회사 기준에 맞게 설정 & Main, Sub 설정 적용 \n",
    "SD500, SD600은 D값에 따라 나누어지고, MAIN, SUB BAR는 Radius 값에 따라 정해진다."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(18,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(18,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "        public string RebarGrade(string size)\n",
    "        {\n",
    "            string rebarGrade = string.Empty;\n",
    "\n",
    "            if (size == \"10\" || size == \"13\")\n",
    "            {\n",
    "                rebarGrade = \"SD500\";\n",
    "            }\n",
    "            else if (size == \"16\" || size == \"19\" || size == \"22\" || size == \"25\")\n",
    "            {\n",
    "                rebarGrade = \"SD600\";\n",
    "            }\n",
    "\n",
    "            return rebarGrade;\n",
    "\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(25,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(25,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "public double BendingRadiusMain(string size)\n",
    "        {\n",
    "            double bendingRadius = 0;\n",
    "\n",
    "            if (size == \"10\")\n",
    "            {\n",
    "                bendingRadius = 30;\n",
    "            }\n",
    "            else if (size == \"13\")\n",
    "            {\n",
    "                bendingRadius = 40;\n",
    "            }\n",
    "            else if (size == \"16\")\n",
    "            {\n",
    "                bendingRadius = 50;\n",
    "            }\n",
    "            else if (size == \"19\")\n",
    "            {\n",
    "                bendingRadius = 60;\n",
    "            }\n",
    "\n",
    "            return bendingRadius;\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "ename": "Unhandled Exception",
     "evalue": "(25,28): error CS1733: 식이 필요합니다.",
     "output_type": "error",
     "traceback": [
      "(25,28): error CS1733: 식이 필요합니다."
     ]
    }
   ],
   "source": [
    "public double BendingRadiusSub(string size)\n",
    "        {\n",
    "            double bendingRadius = 0;\n",
    "\n",
    "            if (size == \"10\")\n",
    "            {\n",
    "                bendingRadius = 20;\n",
    "            }\n",
    "            else if (size == \"13\")\n",
    "            {\n",
    "                bendingRadius = 27.5;\n",
    "            }\n",
    "            else if (size == \"16\")\n",
    "            {\n",
    "                bendingRadius = 32.5;\n",
    "            }\n",
    "            else if (size == \"19\")\n",
    "            {\n",
    "                bendingRadius = 57.5;\n",
    "            }\n",
    "\n",
    "            return bendingRadius;\n",
    "        }\n",
    "        \n",
    "-//오류 메세지 적게 보이게 하기 위해서..  "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".NET (C#)",
   "language": "C#",
   "name": ".net-csharp"
  },
  "language_info": {
   "file_extension": ".cs",
   "mimetype": "text/x-csharp",
   "name": "C#",
   "pygments_lexer": "csharp",
   "version": "8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
